In [53]:
import pandas as pd
import numpy as np
df1=pd.read_csv("E:\\python\\PCA\\iris.csv")

In [54]:
#Re-name columns in the dataset
df1.columns=['Sepal_length','Sepal_width','Petal_length','Petal_width','Type']

In [55]:
df1.head(5)

Sepal_length  Sepal_width  Petal_length  Petal_width         Type
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [56]:
#Check for any NA or null values
df1.isnull().any()

Sepal_length    False
Sepal_width     False
Petal_length    False
Petal_width     False
Type            False
dtype: bool

In [57]:
df1.shape

(150, 5)

In [58]:
#Extract all the features from the data set, in this data set they are 4
x=df1.iloc[:, 0:4]
#Extract the flower type into another dataframe
y=df1.iloc[:,-1]

In [59]:
df2=pd.DataFrame()

In [61]:
#Mean normalizing the whole data manually
df3=((x-x.mean())/x.std())


In [63]:
df3.head()

Sepal_length  Sepal_width  Petal_length  Petal_width
0     -0.897674     1.028611     -1.336794    -1.308593
1     -1.139200    -0.124540     -1.336794    -1.308593
2     -1.380727     0.336720     -1.393470    -1.308593
3     -1.501490     0.106090     -1.280118    -1.308593
4     -1.018437     1.259242     -1.336794    -1.308593

In [65]:
#Mean normalizing using scikit learn's method
from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(x)

In [67]:
X_std[1]

array([-1.14301691, -0.1249576 , -1.3412724 , -1.31297673])

In [71]:
import numpy as np
#Calculating covariance matrix using method 1(normalized using scikit method)
mean_vec = np.mean(X_std, axis=0)
mean_vec

array([ -4.73695157e-16,  -6.63173220e-16,   3.31586610e-16,
        -2.84217094e-16])

In [69]:
#Calculating covariance matrix using method 1(normalized using my method)
mean_vec1=np.mean(df3,axis=0)

In [72]:
mean_vec1

Sepal_length   -1.457168e-15
Sepal_width    -1.722511e-15
Petal_length   -2.043551e-15
Petal_width    -9.843977e-17
dtype: float64

In [73]:
#Co-variance matrix calculated on normalized data from scikit's method
cov_mat = (X_std - mean_vec).T.dot((X_std - mean_vec)) / (X_std.shape[0]-1)
print('Covariance matrix \n%s' %cov_mat)

Covariance matrix 
[[ 1.00671141 -0.11010327  0.87760486  0.82344326]
 [-0.11010327  1.00671141 -0.42333835 -0.358937  ]
 [ 0.87760486 -0.42333835  1.00671141  0.96921855]
 [ 0.82344326 -0.358937    0.96921855  1.00671141]]


In [75]:
#Co-variance matrix calculated on normalized data from my method
cov_mat1 = (df3 - mean_vec1).T.dot((df3 - mean_vec1)) / (df3.shape[0]-1)
print('Covariance matrix \n%s' %cov_mat1)

Covariance matrix 
              Sepal_length  Sepal_width  Petal_length  Petal_width
Sepal_length      1.000000    -0.109369      0.871754     0.817954
Sepal_width      -0.109369     1.000000     -0.420516    -0.356544
Petal_length      0.871754    -0.420516      1.000000     0.962757
Petal_width       0.817954    -0.356544      0.962757     1.000000


In [76]:
print('NumPy covariance matrix: \n%s' %np.cov(df3.T))

NumPy covariance matrix: 
[[ 1.         -0.10936925  0.87175416  0.81795363]
 [-0.10936925  1.         -0.4205161  -0.35654409]
 [ 0.87175416 -0.4205161   1.          0.9627571 ]
 [ 0.81795363 -0.35654409  0.9627571   1.        ]]


In [77]:
#Eigen values and vectors calculated from scikit method
eig_vals, eig_vecs = np.linalg.eig(cov_mat)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[ 0.52237162 -0.37231836 -0.72101681  0.26199559]
 [-0.26335492 -0.92555649  0.24203288 -0.12413481]
 [ 0.58125401 -0.02109478  0.14089226 -0.80115427]
 [ 0.56561105 -0.06541577  0.6338014   0.52354627]]

Eigenvalues 
[ 2.93035378  0.92740362  0.14834223  0.02074601]


In [79]:
#Eigen values and vectors calculated from my method
eig_vals1, eig_vecs1 = np.linalg.eig(cov_mat1)

print('Eigenvectors \n%s' %eig_vecs1)
print('\nEigenvalues \n%s' %eig_vals1)
#As we can see the eigen values and vectors are approximately equal in both methods

Eigenvectors 
[[ 0.52237162 -0.37231836 -0.72101681  0.26199559]
 [-0.26335492 -0.92555649  0.24203288 -0.12413481]
 [ 0.58125401 -0.02109478  0.14089226 -0.80115427]
 [ 0.56561105 -0.06541577  0.6338014   0.52354627]]

Eigenvalues 
[ 2.91081808  0.92122093  0.14735328  0.02060771]


In [80]:
for ev in eig_vecs:
    np.testing.assert_array_almost_equal(1.0, np.linalg.norm(ev))
print('Everything ok!')

Everything ok!


In [81]:
for ev in eig_vecs1:
    np.testing.assert_array_almost_equal(1.0, np.linalg.norm(ev))
print('Everything ok!')

Everything ok!


In [98]:
# Make a list of (eigenvalue, eigenvector) tuples
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]
eig_pairs

[(2.9303537755893156,
  array([ 0.52237162, -0.26335492,  0.58125401,  0.56561105])),
 (0.9274036215173419,
  array([-0.37231836, -0.92555649, -0.02109478, -0.06541577])),
 (0.14834222648164008,
  array([-0.72101681,  0.24203288,  0.14089226,  0.6338014 ])),
 (0.020746013995595992,
  array([ 0.26199559, -0.12413481, -0.80115427,  0.52354627]))]

In [99]:
eig_pairs[0][1].reshape(4,1)

array([[ 0.52237162],
       [-0.26335492],
       [ 0.58125401],
       [ 0.56561105]])

In [100]:
eig_pairs[1][1].reshape(4,1)

array([[-0.37231836],
       [-0.92555649],
       [-0.02109478],
       [-0.06541577]])

In [101]:
matrix_w=np.hstack((eig_pairs[0][1].reshape(4,1),eig_pairs[1][1].reshape(4,1)))
matrix_w

array([[ 0.52237162, -0.37231836],
       [-0.26335492, -0.92555649],
       [ 0.58125401, -0.02109478],
       [ 0.56561105, -0.06541577]])

In [106]:
Y = X_std.dot(matrix_w)
Y

array([[ -2.26454173e+00,  -5.05703903e-01],
       [ -2.08642550e+00,   6.55404729e-01],
       [ -2.36795045e+00,   3.18477311e-01],
       [ -2.30419716e+00,   5.75367713e-01],
       [ -2.38877749e+00,  -6.74767397e-01],
       [ -2.07053681e+00,  -1.51854856e+00],
       [ -2.44571134e+00,  -7.45626750e-02],
       [ -2.23384186e+00,  -2.47613932e-01],
       [ -2.34195768e+00,   1.09514636e+00],
       [ -2.18867576e+00,   4.48629048e-01],
       [ -2.16348656e+00,  -1.07059558e+00],
       [ -2.32737775e+00,  -1.58587455e-01],
       [ -2.22408272e+00,   7.09118158e-01],
       [ -2.63971626e+00,   9.38281982e-01],
       [ -2.19229151e+00,  -1.88997851e+00],
       [ -2.25146521e+00,  -2.72237108e+00],
       [ -2.20275048e+00,  -1.51375028e+00],
       [ -2.19017916e+00,  -5.14304308e-01],
       [ -1.89407429e+00,  -1.43111071e+00],
       [ -2.33994907e+00,  -1.15803343e+00],
       [ -1.91455639e+00,  -4.30465163e-01],
       [ -2.20464540e+00,  -9.52457317e-01],
       [ -

In [103]:
eig_pairs1 = [(np.abs(eig_vals1[i]), eig_vecs1[:,i]) for i in range(len(eig_vals1))]
eig_pairs1

[(2.9108180837520563,
  array([ 0.52237162, -0.26335492,  0.58125401,  0.56561105])),
 (0.92122093070722455,
  array([-0.37231836, -0.92555649, -0.02109478, -0.06541577])),
 (0.14735327830509584,
  array([-0.72101681,  0.24203288,  0.14089226,  0.6338014 ])),
 (0.020607707235625775,
  array([ 0.26199559, -0.12413481, -0.80115427,  0.52354627]))]

In [104]:
matrix_w1=np.hstack((eig_pairs1[0][1].reshape(4,1),eig_pairs1[1][1].reshape(4,1)))
matrix_w1

array([[ 0.52237162, -0.37231836],
       [-0.26335492, -0.92555649],
       [ 0.58125401, -0.02109478],
       [ 0.56561105, -0.06541577]])

In [107]:
Y1=df3.dot(matrix_w1)
Y1

0         1
0   -2.256981 -0.504015
1   -2.079459  0.653216
2   -2.360044  0.317414
3   -2.296504  0.573447
4   -2.380802 -0.672514
5   -2.063623 -1.513478
6   -2.437545 -0.074314
7   -2.226383 -0.246787
8   -2.334138  1.091490
9   -2.181368  0.447131
10  -2.156263 -1.067021
11  -2.319607 -0.158058
12  -2.216657  0.706750
13  -2.630902  0.935149
14  -2.184972 -1.883668
15  -2.243948 -2.713281
16  -2.195396 -1.508696
17  -2.182866 -0.512587
18  -1.887750 -1.426332
19  -2.332136 -1.154167
20  -1.908164 -0.429028
21  -2.197284 -0.949277
22  -2.764907 -0.487883
23  -1.814333 -0.106394
24  -2.220778 -0.161645
25  -1.950490  0.605863
26  -2.045212 -0.265126
27  -2.160954 -0.550173
28  -2.133160 -0.335516
29  -2.261215  0.313827
..        ...       ...
120  2.033683 -0.904369
121  0.970663  0.569267
122  2.888388 -0.396463
123  1.324756  0.485135
124  1.698550 -1.010762
125  1.951191 -0.999984
126  1.167992  0.317832
127  1.016376 -0.065324
128  1.780046  0.192627
129  1.858552 -0.553527
130  2.427365 -0.245831
131  2.308349 -2.617415
132  1.854160  0.184056
133  1.107561  0.294998
134  1.193471  0.814439
135  2.791597 -0.841928
136  1.574879 -1.068894
137  1.342547 -0.420846
138  0.920350 -0.019166
139  1.847363 -0.670178
140  2.009425 -0.608359
141  1.896763 -0.683734
142  1.149339  0.698984
143  2.036486 -0.861798
144  1.995008 -1.045049
145  1.864277 -0.381544
146  1.553288  0.902291
147  1.515767 -0.265904
148  1.371796 -1.012968
149  0.956096  0.022210

[150 rows x 2 columns]